language: node_js
dist: bionic
node_js:
  - "10"
cache:
  yarn: true

# upgrade yarn to a more recent version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: "Test"
      script: |
        yarn
        yarn cov-test
        yarn run codecov

