name: CI (Linux)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 11, 12]
        # TODO, disabled windows because we don't run tests there as for now
        # and IDK how to disable particular step only on w32
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: |
        npm install -g chromedriver geckodriver
    - name: test and build
      run: |
        set -ex
        yarn
        yarn pre-test
        yarn run tslint
        yarn run prettier
        yarn run build-tests
        yarn cov-test
        firefox --version
        whereis firefox
        yarn test-browser --headless-firefox
        google-chrome --version
        whereis google-chrome
        yarn test-browser --headless-chrome
        yarn run build
        yarn run typedoc
    - name: Save Coverage Report
      uses: actions/upload-artifact@master
      with:
        name: coverage-report
        path: coverage
